name: 'My Job will help to Planning for display Message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python my_script.py
      - run: ls
      - run: echo new command 

